// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct EnumArrays: Codable {
  public var justSymbol: JustSymbol?
  public var arrayEnum: [ArrayEnumItem]?

  public enum JustSymbol: String, Codable, CaseIterable, Sendable {
    case greaterThanOrEqualTo = ">="
    case dollar = "$"
    case unknown


    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      let rawValue = try container.decode(String.self)
      self = Self(rawValue: rawValue) ?? .unknown
    }
  }

  public enum ArrayEnumItem: String, Codable, CaseIterable, Sendable {
    case fish
    case crab
    case unknown


    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      let rawValue = try container.decode(String.self)
      self = Self(rawValue: rawValue) ?? .unknown
    }
  }

  public init(justSymbol: JustSymbol? = nil, arrayEnum: [ArrayEnumItem]? = nil) {
    self.justSymbol = justSymbol
    self.arrayEnum = arrayEnum
  }

  public init(from decoder: Decoder) throws {
    let values = try decoder.container(keyedBy: StringCodingKey.self)
    self.justSymbol = try values.decodeIfPresent(JustSymbol.self, forKey: "just_symbol")
    self.arrayEnum = try values.decodeIfPresent([ArrayEnumItem].self, forKey: "array_enum")
  }

  public func encode(to encoder: Encoder) throws {
    var values = encoder.container(keyedBy: StringCodingKey.self)
    try values.encodeIfPresent(justSymbol, forKey: "just_symbol")
    try values.encodeIfPresent(arrayEnum, forKey: "array_enum")
  }
}
