// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

import Foundation

public protocol OneOfEnum {
  var isUnknownCase: Bool { get }
}

public protocol UnknownOneOfCase {
  var discriminatorValue: String { get }
}

extension OneOfEnum {
  public func fatalUnknownAccess(_ message: @autoclosure () -> String = String(), file: StaticString = #file, line: UInt = #line) -> Never {
  fatalError(message(), file: file, line: line)
  }
}

extension UnknownOneOfCase {
  public func fatalUnknownAccess(_ message: @autoclosure () -> String = String(), file: StaticString = #file, line: UInt = #line) -> Never {
  fatalError(message(), file: file, line: line)
  }
}

extension Swift.Collection where Element: OneOfEnum {
  public var excludingUnknown: [Element] {
  filter { !$0.isUnknownCase }
  }
}
