// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public enum AnyTransitPoint: Codable, OneOfEnum {
    case airportTransitPoint(AirportTransitPoint)
    case geoTransitPoint(GeoTransitPoint)

    case unknown(UnknownAnyTransitPoint)

    public struct UnknownAnyTransitPoint: Codable, UnknownOneOfCase {
      public enum `Type`: String, Codable, CaseIterable, Sendable {
        case unknown
      }
      public var type: `Type` = .unknown
      public var discriminatorValue: String
      public init(discriminatorValue: String) {
        self.discriminatorValue = discriminatorValue
      }
    }

    public var isUnknownCase: Bool {
      if case .unknown = self {
        true
      } else {
        false
      }
    }

    public init(from decoder: Decoder) throws {

        struct Discriminator: Decodable {
            let type: String
        }

        let container = try decoder.singleValueContainer()
        let discriminatorValue = try container.decode(Discriminator.self).type

        switch discriminatorValue {
        case "airport": self = .airportTransitPoint(try container.decode(AirportTransitPoint.self))
        case "geo": self = .geoTransitPoint(try container.decode(GeoTransitPoint.self))
        default: self = .unknown(.init(discriminatorValue: discriminatorValue))
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .airportTransitPoint(let value): try container.encode(value)
        case .geoTransitPoint(let value): try container.encode(value)
        case .unknown(let value): try container.encode(value)
        }
    }
}
