// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public protocol Message {
    var body: String { get }
    var timestamp: String { get }
    var tags: [String]? { get }
}

extension BotMessage: Message {}

extension UserMessage: Message {}

extension SystemMessage: Message {}

extension AnyMessage {
    public init(_ value: BotMessage) { self = .botMessage(value) }
    public init(_ value: UserMessage) { self = .userMessage(value) }
    public init(_ value: SystemMessage) { self = .systemMessage(value) }
}

extension AnyMessage: Message {
    private var _wrapped: any Message {
        switch self {
        case .botMessage(let v): v
        case .userMessage(let v): v
        case .systemMessage(let v): v
        }
    }

    public var body: String { _wrapped.body }
    public var timestamp: String { _wrapped.timestamp }
    public var tags: [String]? { _wrapped.tags }
}
