// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetMessageResponse: Codable {
    public var message: AnyServerMessage?

    public init(message: AnyServerMessage? = nil) {
        self.message = message
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.message = try values.decodeIfPresent(AnyServerMessage.self, forKey: "message")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(message, forKey: "message")
    }
}
