// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths {
    public static var messages: Messages {
        Messages(path: "/messages")
    }

    public struct Messages {
        /// Path: `/messages`
        public let path: String

        public var get: Request<[abstract_protocol_overlapping_enums.AnyMessage]> {
            Request(path: path, method: "GET", id: "getMessages")
        }
    }
}
