// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths {
    public static var completion: Completion {
        Completion(path: "/completion")
    }

    public struct Completion {
        /// Path: `/completion`
        public let path: String

        public var get: Request<deprecated_references.Completion> {
            Request(path: path, method: "GET", id: "getCompletion")
        }
    }
}
