// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths {
    public static var status: Status {
        Status(path: "/status")
    }

    public struct Status {
        /// Path: `/status`
        public let path: String

        public var get: Request<nullable_composition.ConnectionStatus> {
            Request(path: path, method: "GET", id: "getStatus")
        }
    }
}
