// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct AbstractMessage: Codable {
    public var body: String
    public var timestamp: String
    public var tags: [String]?

    public init(body: String, timestamp: String, tags: [String]? = nil) {
        self.body = body
        self.timestamp = timestamp
        self.tags = tags
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.body = try values.decode(String.self, forKey: "body")
        self.timestamp = try values.decode(String.self, forKey: "timestamp")
        self.tags = try values.decodeIfPresent([String].self, forKey: "tags")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(body, forKey: "body")
        try values.encode(timestamp, forKey: "timestamp")
        try values.encodeIfPresent(tags, forKey: "tags")
    }
}
