// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public enum AnyMessage: Codable, OneOfEnum {
    case botMessage(BotMessage)
    case userMessage(UserMessage)
    case systemMessage(SystemMessage)

    case unknown(UnknownAnyMessage)

    public struct UnknownAnyMessage: Codable, UnknownOneOfCase {
      public enum `Type`: String, Codable, CaseIterable, Sendable {
        case unknown
      }
      public var type: `Type` = .unknown
      public var discriminatorValue: String
      public init(discriminatorValue: String) {
        self.discriminatorValue = discriminatorValue
      }
    }

    public var isUnknownCase: Bool {
      if case .unknown = self {
        true
      } else {
        false
      }
    }

    public init(from decoder: Decoder) throws {

        struct Discriminator: Decodable {
            let type: String
        }

        let container = try decoder.singleValueContainer()
        let discriminatorValue = try container.decode(Discriminator.self).type

        switch discriminatorValue {
        case "bot": self = .botMessage(try container.decode(BotMessage.self))
        case "user": self = .userMessage(try container.decode(UserMessage.self))
        case "system": self = .systemMessage(try container.decode(SystemMessage.self))
        default: self = .unknown(.init(discriminatorValue: discriminatorValue))
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .botMessage(let value): try container.encode(value)
        case .userMessage(let value): try container.encode(value)
        case .systemMessage(let value): try container.encode(value)
        case .unknown(let value): try container.encode(value)
        }
    }
}
