// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct BotMessage: Codable {
    public var body: String
    public var timestamp: String
    public var tags: [String]?
    public var type: `Type`
    public var id: Int
    public var intent: String?

    public enum `Type`: String, Codable, CaseIterable, Sendable {
        case bot
    }

    public init(body: String, timestamp: String, tags: [String]? = nil, type: `Type`, id: Int, intent: String? = nil) {
        self.body = body
        self.timestamp = timestamp
        self.tags = tags
        self.type = type
        self.id = id
        self.intent = intent
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.body = try values.decode(String.self, forKey: "body")
        self.timestamp = try values.decode(String.self, forKey: "timestamp")
        self.tags = try values.decodeIfPresent([String].self, forKey: "tags")
        self.type = try values.decode(`Type`.self, forKey: "type")
        self.id = try values.decode(Int.self, forKey: "id")
        self.intent = try values.decodeIfPresent(String.self, forKey: "intent")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(body, forKey: "body")
        try values.encode(timestamp, forKey: "timestamp")
        try values.encodeIfPresent(tags, forKey: "tags")
        try values.encode(type, forKey: "type")
        try values.encode(id, forKey: "id")
        try values.encodeIfPresent(intent, forKey: "intent")
    }
}
