// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GeoTransitPoint: Codable {
    public var name: String
    public var latitude: Double
    public var longitude: Double
    public var type: `Type`
    public var category: String?

    public enum `Type`: String, Codable, CaseIterable, Sendable {
        case geo
    }

    public init(name: String, latitude: Double, longitude: Double, type: `Type`, category: String? = nil) {
        self.name = name
        self.latitude = latitude
        self.longitude = longitude
        self.type = type
        self.category = category
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.name = try values.decode(String.self, forKey: "name")
        self.latitude = try values.decode(Double.self, forKey: "latitude")
        self.longitude = try values.decode(Double.self, forKey: "longitude")
        self.type = try values.decode(`Type`.self, forKey: "type")
        self.category = try values.decodeIfPresent(String.self, forKey: "category")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(name, forKey: "name")
        try values.encode(latitude, forKey: "latitude")
        try values.encode(longitude, forKey: "longitude")
        try values.encode(type, forKey: "type")
        try values.encodeIfPresent(category, forKey: "category")
    }
}
