// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct SystemMessage: Codable {
    public var body: String
    public var timestamp: String
    public var tags: [String]?
    public var type: `Type`
    public var level: Level?

    public enum `Type`: String, Codable, CaseIterable, Sendable {
        case system
    }

    public enum Level: String, Codable, CaseIterable, Sendable {
        case info
        case warning
        case error
        case unknown


        public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(String.self)
            self = Self(rawValue: rawValue) ?? .unknown
        }
    }

    public init(body: String, timestamp: String, tags: [String]? = nil, type: `Type`, level: Level? = nil) {
        self.body = body
        self.timestamp = timestamp
        self.tags = tags
        self.type = type
        self.level = level
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.body = try values.decode(String.self, forKey: "body")
        self.timestamp = try values.decode(String.self, forKey: "timestamp")
        self.tags = try values.decodeIfPresent([String].self, forKey: "tags")
        self.type = try values.decode(`Type`.self, forKey: "type")
        self.level = try values.decodeIfPresent(Level.self, forKey: "level")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(body, forKey: "body")
        try values.encode(timestamp, forKey: "timestamp")
        try values.encodeIfPresent(tags, forKey: "tags")
        try values.encode(type, forKey: "type")
        try values.encodeIfPresent(level, forKey: "level")
    }
}
