// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public enum AnyMessage: Codable {
    case botMessage(BotMessage)
    case userMessage(UserMessage)
    case systemMessage(SystemMessage)

    public init(from decoder: Decoder) throws {

        struct Discriminator: Decodable {
            let type: String
        }

        let container = try decoder.singleValueContainer()
        let discriminatorValue = try container.decode(Discriminator.self).type

        switch discriminatorValue {
        case "bot": self = .botMessage(try container.decode(BotMessage.self))
        case "user": self = .userMessage(try container.decode(UserMessage.self))
        case "system": self = .systemMessage(try container.decode(SystemMessage.self))
        default:
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "Discriminator value '\(discriminatorValue)' does not match any expected values (bot, user, system)."
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .botMessage(let value): try container.encode(value)
        case .userMessage(let value): try container.encode(value)
        case .systemMessage(let value): try container.encode(value)
        }
    }
}
