// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public enum AnyTransitPoint: Codable {
    case airportTransitPoint(AirportTransitPoint)
    case geoTransitPoint(GeoTransitPoint)

    public init(from decoder: Decoder) throws {

        struct Discriminator: Decodable {
            let type: String
        }

        let container = try decoder.singleValueContainer()
        let discriminatorValue = try container.decode(Discriminator.self).type

        switch discriminatorValue {
        case "airport": self = .airportTransitPoint(try container.decode(AirportTransitPoint.self))
        case "geo": self = .geoTransitPoint(try container.decode(GeoTransitPoint.self))
        default:
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "Discriminator value '\(discriminatorValue)' does not match any expected values (airport, geo)."
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .airportTransitPoint(let value): try container.encode(value)
        case .geoTransitPoint(let value): try container.encode(value)
        }
    }
}
