// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct BaseTransitPoint: Codable {
    public var name: String
    public var latitude: Double
    public var longitude: Double

    public init(name: String, latitude: Double, longitude: Double) {
        self.name = name
        self.latitude = latitude
        self.longitude = longitude
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.name = try values.decode(String.self, forKey: "name")
        self.latitude = try values.decode(Double.self, forKey: "latitude")
        self.longitude = try values.decode(Double.self, forKey: "longitude")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(name, forKey: "name")
        try values.encode(latitude, forKey: "latitude")
        try values.encode(longitude, forKey: "longitude")
    }
}
