// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public protocol Message {
    var body: String { get }
    var timestamp: String { get }
    var tags: [String]? { get }
    var toAnyMessage: AnyMessage { get }
    var toAnyUiMessage: AnyUiMessage { get }
}

extension BotMessage: Message {
    public var toAnyMessage: AnyMessage { AnyMessage(self) }
    public var toAnyUiMessage: AnyUiMessage { AnyUiMessage(self) }
    public var toAnyPriorityMessage: AnyPriorityMessage { AnyPriorityMessage(self) }
}

extension UserMessage: Message {
    public var toAnyMessage: AnyMessage { AnyMessage(self) }
    public var toAnyUiMessage: AnyUiMessage { AnyUiMessage(self) }
}

extension SystemMessage: Message {
    public var toAnyMessage: AnyMessage { AnyMessage(self) }
    public var toAnyUiMessage: AnyUiMessage { AnyUiMessage(self) }
    public var toAnyPriorityMessage: AnyPriorityMessage { AnyPriorityMessage(self) }
}

extension AnyMessage {
    public init(_ value: BotMessage) { self = .botMessage(value) }
    public init(_ value: UserMessage) { self = .userMessage(value) }
    public init(_ value: SystemMessage) { self = .systemMessage(value) }
    public init(_ value: any Message) { self = value.toAnyMessage }
}

extension AnyMessage: Message {
    public var wrappedMessage: any Message {
        switch self {
        case .botMessage(let v): v
        case .userMessage(let v): v
        case .systemMessage(let v): v
        }
    }

    public var toAnyUiMessage: AnyUiMessage {
        switch self {
        case .botMessage(let v): .botMessage(v)
        case .userMessage(let v): .userMessage(v)
        case .systemMessage(let v): .systemMessage(v)
        }
    }
    public var toAnyMessage: AnyMessage { self }

    public var body: String { wrappedMessage.body }
    public var timestamp: String { wrappedMessage.timestamp }
    public var tags: [String]? { wrappedMessage.tags }
}

extension AnyUiMessage {
    public init(_ value: BotMessage) { self = .botMessage(value) }
    public init(_ value: UserMessage) { self = .userMessage(value) }
    public init(_ value: SystemMessage) { self = .systemMessage(value) }
    public init(_ value: any Message) { self = value.toAnyUiMessage }
}

extension AnyUiMessage: Message {
    public var wrappedMessage: any Message {
        switch self {
        case .botMessage(let v): v
        case .userMessage(let v): v
        case .systemMessage(let v): v
        }
    }

    public var toAnyMessage: AnyMessage {
        switch self {
        case .botMessage(let v): .botMessage(v)
        case .userMessage(let v): .userMessage(v)
        case .systemMessage(let v): .systemMessage(v)
        }
    }
    public var toAnyUiMessage: AnyUiMessage { self }

    public var body: String { wrappedMessage.body }
    public var timestamp: String { wrappedMessage.timestamp }
    public var tags: [String]? { wrappedMessage.tags }
}

extension AnyPriorityMessage {
    public init(_ value: BotMessage) { self = .botMessage(value) }
    public init(_ value: SystemMessage) { self = .systemMessage(value) }
    public init(_ value: any Message) {
        if let v = value as? AnyPriorityMessage { self = v } else if let v = value as? BotMessage { self = .botMessage(v) } else if let v = value as? SystemMessage { self = .systemMessage(v) } else { fatalError("Unknown \(Message.self) conformer: \(type(of: value))") }
    }
}

extension AnyPriorityMessage: Message {
    public var wrappedMessage: any Message {
        switch self {
        case .botMessage(let v): v
        case .systemMessage(let v): v
        }
    }

    public var toAnyMessage: AnyMessage {
        switch self {
        case .botMessage(let v): .botMessage(v)
        case .systemMessage(let v): .systemMessage(v)
        }
    }
    public var toAnyUiMessage: AnyUiMessage {
        switch self {
        case .botMessage(let v): .botMessage(v)
        case .systemMessage(let v): .systemMessage(v)
        }
    }
    public var toAnyPriorityMessage: AnyPriorityMessage { self }

    public var body: String { wrappedMessage.body }
    public var timestamp: String { wrappedMessage.timestamp }
    public var tags: [String]? { wrappedMessage.tags }
}
