// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public protocol TransitPoint {
    var name: String { get }
    var latitude: Double { get }
    var longitude: Double { get }
    var toAnyTransitPoint: AnyTransitPoint { get }
}

extension AirportTransitPoint: TransitPoint {
    public var toAnyTransitPoint: AnyTransitPoint { AnyTransitPoint(self) }
}

extension GeoTransitPoint: TransitPoint {
    public var toAnyTransitPoint: AnyTransitPoint { AnyTransitPoint(self) }
}

extension AnyTransitPoint {
    public init(_ value: AirportTransitPoint) { self = .airportTransitPoint(value) }
    public init(_ value: GeoTransitPoint) { self = .geoTransitPoint(value) }
    public init(_ value: any TransitPoint) { self = value.toAnyTransitPoint }
}

extension AnyTransitPoint: TransitPoint {
    public var wrappedTransitPoint: any TransitPoint {
        switch self {
        case .airportTransitPoint(let v): v
        case .geoTransitPoint(let v): v
        }
    }

    public var toAnyTransitPoint: AnyTransitPoint { self }

    public var name: String { wrappedTransitPoint.name }
    public var latitude: Double { wrappedTransitPoint.latitude }
    public var longitude: Double { wrappedTransitPoint.longitude }
}
