// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public enum Completion: Codable, OneOfEnum {
    case setupCompletion(SetupCompletion)
    case legacyCompletion(LegacyCompletion)

    case unknown(UnknownCompletion)

    public struct UnknownCompletion: Codable, UnknownOneOfCase {
      public enum `Type`: String, Codable, CaseIterable, Sendable {
        case unknown
      }
      public var type: `Type` = .unknown
      public var discriminatorValue: String
      public init(discriminatorValue: String) {
        self.discriminatorValue = discriminatorValue
      }
    }

    public var isUnknownCase: Bool {
      if case .unknown = self {
        true
      } else {
        false
      }
    }

    public init(from decoder: Decoder) throws {

        struct Discriminator: Decodable {
            let flow: String
        }

        let container = try decoder.singleValueContainer()
        let discriminatorValue = try container.decode(Discriminator.self).flow

        switch discriminatorValue {
        case "setup": self = .setupCompletion(try container.decode(SetupCompletion.self))
        case "legacy": self = .legacyCompletion(try container.decode(LegacyCompletion.self))
        default: self = .unknown(.init(discriminatorValue: discriminatorValue))
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .setupCompletion(let value): try container.encode(value)
        case .legacyCompletion(let value): try container.encode(value)
        case .unknown(let value): try container.encode(value)
        }
    }
}
