// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// Referenced only by a deprecated type, which itself loses the attribute, so this one does too.
///
/// - warning: Deprecated.
public struct LegacyDetail: Codable {
    public var note: String?

    public init(note: String? = nil) {
        self.note = note
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.note = try values.decodeIfPresent(String.self, forKey: "note")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(note, forKey: "note")
    }
}
