// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// Referenced by the non-deprecated oneOf, so it can't carry the attribute.
///
/// - warning: Deprecated.
public struct LegacyCompletion: Codable {
    public var flow: Flow
    /// Referenced only by a deprecated type, which itself loses the attribute, so this one does too.
    ///
    /// - warning: Deprecated.
    public var detail: LegacyDetail?

    public enum Flow: String, Codable, CaseIterable, Sendable {
        case legacy
    }

    public init(flow: Flow, detail: LegacyDetail? = nil) {
        self.flow = flow
        self.detail = detail
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.flow = try values.decode(Flow.self, forKey: "flow")
        self.detail = try values.decodeIfPresent(LegacyDetail.self, forKey: "detail")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(flow, forKey: "flow")
        try values.encodeIfPresent(detail, forKey: "detail")
    }
}
