// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct SetupCompletion: Codable {
    public var flow: Flow

    public enum Flow: String, Codable, CaseIterable, Sendable {
        case setup
    }

    public init(flow: Flow) {
        self.flow = flow
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.flow = try values.decode(Flow.self, forKey: "flow")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(flow, forKey: "flow")
    }
}
