// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// Referenced by nothing, so it keeps the attribute.
@available(*, deprecated, message: "Deprecated")
public struct UnusedLegacy: Codable {
    public var note: String?

    public init(note: String? = nil) {
        self.note = note
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.note = try values.decodeIfPresent(String.self, forKey: "note")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(note, forKey: "note")
    }
}
