// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ConnectionStatus: Codable {
    public var id: Int
    public var errorMessage: String?
    public var requiredSession: SyncSession?
    public var optionalSession: SyncSession?
    public var oneOfSession: SyncSession?

    public init(id: Int, errorMessage: String? = nil, requiredSession: SyncSession? = nil, optionalSession: SyncSession? = nil, oneOfSession: SyncSession? = nil) {
        self.id = id
        self.errorMessage = errorMessage
        self.requiredSession = requiredSession
        self.optionalSession = optionalSession
        self.oneOfSession = oneOfSession
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Int.self, forKey: "id")
        self.errorMessage = try values.decodeIfPresent(String.self, forKey: "error_message")
        self.requiredSession = try values.decodeIfPresent(SyncSession.self, forKey: "required_session")
        self.optionalSession = try values.decodeIfPresent(SyncSession.self, forKey: "optional_session")
        self.oneOfSession = try values.decodeIfPresent(SyncSession.self, forKey: "one_of_session")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encodeIfPresent(errorMessage, forKey: "error_message")
        try values.encodeIfPresent(requiredSession, forKey: "required_session")
        try values.encodeIfPresent(optionalSession, forKey: "optional_session")
        try values.encodeIfPresent(oneOfSession, forKey: "one_of_session")
    }
}
