// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct SyncSession: Codable {
    public var id: Int
    public var state: String

    public init(id: Int, state: String) {
        self.id = id
        self.state = state
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Int.self, forKey: "id")
        self.state = try values.decode(String.self, forKey: "state")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(state, forKey: "state")
    }
}
