// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Analysis deletion
///
/// Successful deletion of a code scanning analysis
public struct CodeScanningAnalysisDeletion: Codable {
    /// Next deletable analysis in chain, without last analysis deletion confirmation
    public var nextAnalysisURL: URL
    /// Next deletable analysis in chain, with last analysis deletion confirmation
    public var confirmDeleteURL: URL

    public init(nextAnalysisURL: URL, confirmDeleteURL: URL) {
        self.nextAnalysisURL = nextAnalysisURL
        self.confirmDeleteURL = confirmDeleteURL
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.nextAnalysisURL = try values.decode(URL.self, forKey: "next_analysis_url")
        self.confirmDeleteURL = try values.decode(URL.self, forKey: "confirm_delete_url")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(nextAnalysisURL, forKey: "next_analysis_url")
        try values.encode(confirmDeleteURL, forKey: "confirm_delete_url")
    }
}
