// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct CommunityProfile: Codable {
    /// Example: 100
    public var healthPercentage: Int
    /// Example: "My first repository on GitHub!"
    public var description: String
    /// Example: "example.com"
    public var documentation: String
    public var files: Files
    /// Example: "2017-02-28T19:09:29Z"
    public var updatedAt: Date
    /// Example: true
    public var isContentReportsEnabled: Bool?

    public struct Files: Codable {
        /// Code Of Conduct Simple
        ///
        /// Code of Conduct Simple
        public var codeOfConduct: CodeOfConductSimple
        /// Community Health File
        public var codeOfConductFile: CommunityHealthFile
        /// License Simple
        public var license: LicenseSimple
        /// Community Health File
        public var contributing: CommunityHealthFile
        /// Community Health File
        public var readme: CommunityHealthFile
        /// Community Health File
        public var issueTemplate: CommunityHealthFile
        /// Community Health File
        public var pullRequestTemplate: CommunityHealthFile

        public init(codeOfConduct: CodeOfConductSimple, codeOfConductFile: CommunityHealthFile, license: LicenseSimple, contributing: CommunityHealthFile, readme: CommunityHealthFile, issueTemplate: CommunityHealthFile, pullRequestTemplate: CommunityHealthFile) {
            self.codeOfConduct = codeOfConduct
            self.codeOfConductFile = codeOfConductFile
            self.license = license
            self.contributing = contributing
            self.readme = readme
            self.issueTemplate = issueTemplate
            self.pullRequestTemplate = pullRequestTemplate
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.codeOfConduct = try values.decode(CodeOfConductSimple.self, forKey: "code_of_conduct")
            self.codeOfConductFile = try values.decode(CommunityHealthFile.self, forKey: "code_of_conduct_file")
            self.license = try values.decode(LicenseSimple.self, forKey: "license")
            self.contributing = try values.decode(CommunityHealthFile.self, forKey: "contributing")
            self.readme = try values.decode(CommunityHealthFile.self, forKey: "readme")
            self.issueTemplate = try values.decode(CommunityHealthFile.self, forKey: "issue_template")
            self.pullRequestTemplate = try values.decode(CommunityHealthFile.self, forKey: "pull_request_template")
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encode(codeOfConduct, forKey: "code_of_conduct")
            try values.encode(codeOfConductFile, forKey: "code_of_conduct_file")
            try values.encode(license, forKey: "license")
            try values.encode(contributing, forKey: "contributing")
            try values.encode(readme, forKey: "readme")
            try values.encode(issueTemplate, forKey: "issue_template")
            try values.encode(pullRequestTemplate, forKey: "pull_request_template")
        }
    }

    public init(healthPercentage: Int, description: String, documentation: String, files: Files, updatedAt: Date, isContentReportsEnabled: Bool? = nil) {
        self.healthPercentage = healthPercentage
        self.description = description
        self.documentation = documentation
        self.files = files
        self.updatedAt = updatedAt
        self.isContentReportsEnabled = isContentReportsEnabled
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.healthPercentage = try values.decode(Int.self, forKey: "health_percentage")
        self.description = try values.decode(String.self, forKey: "description")
        self.documentation = try values.decode(String.self, forKey: "documentation")
        self.files = try values.decode(Files.self, forKey: "files")
        self.updatedAt = try values.decode(Date.self, forKey: "updated_at")
        self.isContentReportsEnabled = try values.decodeIfPresent(Bool.self, forKey: "content_reports_enabled")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(healthPercentage, forKey: "health_percentage")
        try values.encode(description, forKey: "description")
        try values.encode(documentation, forKey: "documentation")
        try values.encode(files, forKey: "files")
        try values.encode(updatedAt, forKey: "updated_at")
        try values.encodeIfPresent(isContentReportsEnabled, forKey: "content_reports_enabled")
    }
}
