// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct HookResponse: Codable {
    public var code: Int
    public var status: String
    public var message: String

    public init(code: Int, status: String, message: String) {
        self.code = code
        self.status = status
        self.message = message
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.code = try values.decode(Int.self, forKey: "code")
        self.status = try values.decode(String.self, forKey: "status")
        self.message = try values.decode(String.self, forKey: "message")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(code, forKey: "code")
        try values.encode(status, forKey: "status")
        try values.encode(message, forKey: "message")
    }
}
