// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public enum WebhookConfigInsecureSSL: Codable, Hashable, OneOfEnum {
    case string(String)
    case double(Double)

    case unknown(UnknownWebhookConfigInsecureSSL)

    public struct UnknownWebhookConfigInsecureSSL: Codable, Hashable, UnknownOneOfCase {
      public enum `Type`: String, Codable, CaseIterable, Sendable {
        case unknown
      }
      public var type: `Type` = .unknown
      public var discriminatorValue: String
      public init(discriminatorValue: String) {
        self.discriminatorValue = discriminatorValue
      }
    }

    public var isUnknownCase: Bool {
      if case .unknown = self {
        true
      } else {
        false
      }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(String.self) {
            self = .string(value)
        } else if let value = try? container.decode(Double.self) {
            self = .double(value)
        } else {
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "Data could not be decoded as any of the expected types (String, Double)."
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let value): try container.encode(value)
        case .double(let value): try container.encode(value)
        case .unknown(let value): try container.encode(value)
        }
    }
}
