// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

struct ContainerA: Codable {
    var child: Child?
    var refChild: AnyJSON

    struct Child: Codable {
        var `enum`: Enum
        var renameMe: String
        var child: Child

        enum Enum: String, Codable, CaseIterable, Sendable {
            case a
            case b
            case unknown


            init(from decoder: Decoder) throws {
                let container = try decoder.singleValueContainer()
                let rawValue = try container.decode(String.self)
                self = Self(rawValue: rawValue) ?? .unknown
            }
        }

        struct Child: Codable {
            var `enum`: Enum
            var renameMe: String

            enum Enum: String, Codable, CaseIterable, Sendable {
                case a
                case b
                case unknown


                init(from decoder: Decoder) throws {
                    let container = try decoder.singleValueContainer()
                    let rawValue = try container.decode(String.self)
                    self = Self(rawValue: rawValue) ?? .unknown
                }
            }

            init(`enum`: Enum, renameMe: String) {
                self.enum = `enum`
                self.renameMe = renameMe
            }

            init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.enum = try values.decode(Enum.self, forKey: "enum")
                self.renameMe = try values.decode(String.self, forKey: "rename-me")
            }

            func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encode(`enum`, forKey: "enum")
                try values.encode(renameMe, forKey: "rename-me")
            }
        }

        init(`enum`: Enum, renameMe: String, child: Child) {
            self.enum = `enum`
            self.renameMe = renameMe
            self.child = child
        }

        init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.enum = try values.decode(Enum.self, forKey: "enum")
            self.renameMe = try values.decode(String.self, forKey: "rename-me")
            self.child = try values.decode(Child.self, forKey: "child")
        }

        func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encode(`enum`, forKey: "enum")
            try values.encode(renameMe, forKey: "rename-me")
            try values.encode(child, forKey: "child")
        }
    }

    init(child: Child? = nil, refChild: AnyJSON) {
        self.child = child
        self.refChild = refChild
    }

    init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.child = try values.decodeIfPresent(Child.self, forKey: "child")
        self.refChild = try values.decode(AnyJSON.self, forKey: "refChild")
    }

    func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(child, forKey: "child")
        try values.encode(refChild, forKey: "refChild")
    }
}
