// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct EnumArrays: Codable {
    public var justSymbol: JustSymbol?
    public var arrayEnum: [ArrayEnumItem]?

    public enum JustSymbol: String, Codable, CaseIterable, Sendable {
        case greaterThanOrEqualTo = ">="
        case dollar = "$"
        case unknown


        public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(String.self)
            self = Self(rawValue: rawValue) ?? .unknown
        }
    }

    public enum ArrayEnumItem: String, Codable, CaseIterable, Sendable {
        case fish
        case crab
        case unknown


        public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(String.self)
            self = Self(rawValue: rawValue) ?? .unknown
        }
    }

    public init(justSymbol: JustSymbol? = nil, arrayEnum: [ArrayEnumItem]? = nil) {
        self.justSymbol = justSymbol
        self.arrayEnum = arrayEnum
    }

    private enum CodingKeys: String, CodingKey {
        case justSymbol = "just_symbol"
        case arrayEnum = "array_enum"
    }
}
